


IF OBJECT_ID('PLATOS', 'U') IS NOT NULL 
  DROP TABLE PLATOS; 
GO

CREATE TABLE PLATOS
(
  "ID"                          INT IDENTITY(1,1),
  "NOMBRE"						VARCHAR(100) NOT NULL,
  "PRECIO"                      DECIMAL(10,2) NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT PLATOS_PK		PRIMARY KEY (ID)
);


IF OBJECT_ID('ORDENES', 'U') IS NOT NULL 
  DROP TABLE ORDENES; 
GO

CREATE TABLE ORDENES
(
  "ID"                          INT IDENTITY(1,1),
  "ID_PLATOS"				    INT NOT NULL,
  "CANTIDAD"			     	INT NOT NULL,
  "MESA"				        INT NOT NULL,
  "ESTADO_REGISTRO"				INT DEFAULT 1 NOT NULL, 
  CONSTRAINT ORDENES_PK		PRIMARY KEY (ID)
);

ALTER TABLE ORDENES
  ADD CONSTRAINT "FK_ORDENES_TO_PLATOS" 
  FOREIGN KEY(ID_PLATOS)
  REFERENCES PLATOS("ID");